---
seed: 42
save_dir_prefix: debug_
update_train_test_datasets_split: true
#data_settings:
n_datasets: 10 # null for all available datasets
test_size: 0.4
train_timeout: 15
test_timeout: 15
n_automl_repetitions: 1
#meta_learning_params:
n_best_dataset_models_to_memorize: 10
mf_extractor_params:
  # groups: general
  features:
    - nr_inst
assessor_params:
  n_neighbors: 2
advisor_params:
  minimal_distance: 1
  n_best_to_advise: 3
