training_method: "train"

batch_size: 1024

model:
  name: "HomogeneousGCN"
  model_parameters:
    in_channels: 15
    out_channels: 1
    gnn_hidden_channels: 8
    gnn_num_layers: 3
    mlp_hidden_channels: 8
    mlp_num_layers: 2
    aggregation: "sum"
    clip_output: null
  loss_name: "mse_loss"
  lr: 0.001

train_dataset:
  name: "HomogeneousPipelineDataset"
  parameters:
    root: "C:\\Users\\zvfrf\\PycharmProjects\\meta-automl-research\\data\\knowledge_base_v0_homogeneous_dataset_all"
    split: null # Dataset is divided into train/test folders.
    direction: "undirected"
    use_operations_hyperparameters: False
    overriden_processed_dir: "C:\\Users\\zvfrf\\PycharmProjects\\meta-automl-research\\data\\knowledge_base_v0_homogeneous_dataset_all\\processed"

val_dataset:
  name: "HomogeneousPipelineDataset"
  parameters:
    root: "C:\\Users\\zvfrf\\PycharmProjects\\meta-automl-research\\data\\knowledge_base_v0_homogeneous_dataset_test"
    split: null # Dataset is divided into train/test folders.
    direction: "undirected"
    use_operations_hyperparameters: False
    overriden_processed_dir: "C:\\Users\\zvfrf\\PycharmProjects\\meta-automl-research\\data\\knowledge_base_v0_homogeneous_dataset_all\\processed"

test_dataset:
  name: "HomogeneousPipelineDataset"
  parameters:
    root: "C:\\Users\\zvfrf\\PycharmProjects\\meta-automl-research\\data\\knowledge_base_v0_homogeneous_dataset_test"
    split: null # Dataset is divided into train/test folders.
    direction: "undirected"
    use_operations_hyperparameters: False
    overriden_processed_dir: "C:\\Users\\zvfrf\\PycharmProjects\\meta-automl-research\\data\\knowledge_base_v0_homogeneous_dataset_all\\processed"

trainer:
  max_epochs: 1000
  devices: "auto"
  log_every_n_steps: 4
  check_val_every_n_epoch: 1

tensorboard_logger:
  save_dir: "C:\\Users\\zvfrf\\PycharmProjects\\meta-automl-research\\experiments"
  name: "reproduce_nir_cherniak_with_new_data"

model_checkpoint_callback:
  save_top_k: 1
  monitor: "val_loss"
  save_last: True
  every_n_epochs: 1

early_stopping_callback: null