training_method: "train_surrogate_model"
batch_size: 256

num_dataloader_workers: 32
model:
  name: "KRankingPipelineDatasetSurrogateModel"
  model_parameters:
    in_size: null  # The parameter is inferred
    num_class: 1
    d_model: 64
    d_model_dset: 64
    dim_feedforward: null  # The parameter is inferred
    dropout: 0.3
    num_heads: 8
    num_layers: 2
    #    layer_norm: True
    batch_norm: True  # not LAYER_NORM
    gnn_type: "graphsage"
    k_hop: 2
    se: "gnn"
    deg: null  # The parameter is inferred
    global_pool: "cls"
    use_edge_attr: False
    pipe_encoder_type: "graph_transformer"
    dataset_encoder_type: "column"  #"column" or "aggregated"
    weight_decay: 0.01
    lr: 0.0001
    temperature: 5
    num_pipes: 3
    sorter: "diffsort"
    sorter_parameters:
      sorting_network_type: "odd_even" # "odd_even" or "bitonic"
      size: 3
  
dataset_params:
  root_path: "./data/pymfe_meta_features_and_fedot_pipelines/all"
  # root_path: "./data/openml/"
  # root_path: "./data/openml_meta_features_and_fedot_pipelines/all"
  is_folded: True

trainer:
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  max_epochs: 100
  accelerator: "cpu"
  devices: "auto"

tensorboard_logger:
  save_dir: "./logs"
  name: "tabular_train"

model_checkpoint_callback:
  save_top_k: 1
  monitor: "val_ndcg"
  mode: "max"
  save_last: False
  every_n_epochs: 1

early_stopping_callback:
  monitor: "val_ndcg"
  mode: "max"
  patience: 10

model_data:
  save_name: "tabular"
  save_dir: "./model_checkpoints/tabular/2/"