training_method: "train_surrogate_model"
batch_size: 256

num_dataloader_workers: 8

model:
  name: "RankingPipelineDatasetSurrogateModel"
  model_parameters:
    in_size: null  # The parameter is inferred
    num_class: 1
    d_model: 96
    dim_feedforward: null  # The parameter is inferred
    dropout: 0.30326810490592576
    num_heads: 6
    num_layers: 5
    #    layer_norm: True
    batch_norm: True  # not LAYER_NORM
    gnn_type: "graphsage"
    k_hop: 1
    se: "gnn"
    deg: null  # The parameter is inferred
    global_pool: "cls"
    use_edge_attr: False
  lr: 0.0006883061453706995

dataset_params:
  root_path: "./data/openml_meta_features_and_fedot_pipelines/all"


trainer:
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  max_epochs: 100
  accelerator: "cpu"
  devices: "auto"

tensorboard_logger:
  save_dir: "experiments/openml_meta_features_and_fedot_pipelines/train_surrogate_model_best"
  name: "hyperparameter_tuning"

model_checkpoint_callback:
  save_top_k: 1
  monitor: "val_ndcg"
  save_last: True
  every_n_epochs: 1

early_stopping_callback:
  monitor: "val_ndcg"
  min_delta: 0.01
  mode: 'max'