name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -U numpy
        pip install git+https://github.com/aimclub/Fedot.Industrial@init_hotfix
        pip install pytest
        pip install pytest-cov
    - name: Run tests and collect coverage
      run: pytest --cov=meta_automl --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
